### PR TITLE
makes pylint happy, clean code and add a proper gitignore

### PR DESCRIPTION
**Pull request by tobycm**

### CODE REVIEW

**Comment by xxcodianxx** [comment]
Lots of great refactoring changes here, will review it thoroughly in a few hours.

Thanks for the great PR! 👍

**Comment by xxcodianxx** [comment]
Lots of great refactoring changes here, will review it thoroughly in a few hours.

Thanks for the great PR! 👍

EDIT: On just a surface inspection, this actually appears to break the entire API. Function signatures on fastapi handlers are very specific - I'm not using single letter argument names because I'm lazy to type it, I'm doing it because they become HTTP query args!

**Comment by tobycm** [comment]
oh I forgot, imma change that in the front end real quick

**Comment by xxcodianxx** [comment]
While I appreciate the push for adherence to code standards, I don't actually see how this commit actually does anything significant other than randomly renaming variable names which would break the already working API.

The pylintrc and .gitignore suggested also contain a lot more unnecessary keys - why do I _need_ to use GitHub's gitignore template when this one already works for the project?

I think adhering to code standards is good, yes, but not when it's a breaking change.

**Pull request closed without merging**
